homeSuccess:
  javascripts: [%OP_JQUERY_URL%, %OP_JQUERYUI_URL%, util]
  layout: layoutA
  customize:
    cautionAboutFriendPre:
      template: [friend, cautionAboutFriendPre]
      parts   : [information]
      target  : [bodyBottom]
    cautionAboutCommunityMemberPre:
      template    : [community, cautionAboutCommunityMemberPre]
      parts       : [information]
      target      : [bodyBottom]
      is_component: true 
    cautionAboutChangeAdminRequest:
      template    : [community, cautionAboutChangeAdminRequest]
      parts       : [information]
      target      : [bodyBottom]
      is_component: true
    cautionAboutSubAdminRequest:
      template    : [community, cautionAboutSubAdminRequest]
      parts       : [information]
      target      : [bodyBottom]
      is_component: true

profileSuccess:
  javascripts: [util]
  layout: layoutA

configSuccess:
  layout: layoutB

loginSuccess:
  layout: layoutA
